# Generated by Django 4.1.3 on 2022-11-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzlatekachny', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='ingredients',
            field=models.CharField(blank=True, max_length=200, verbose_name='Food ingredients'),
        ),
        migrations.AlterField(
            model_name='food',
            name='notes',
            field=models.CharField(blank=True, max_length=200, verbose_name='Food notes'),
        ),
    ]
