# Generated by Django 4.1.3 on 2022-11-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzlatekachny', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='category',
            name='name_cs',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Food category name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_de',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Food category name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Food category name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Food category name'),
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients_cs',
            field=models.TextField(blank=True, null=True, verbose_name='Food ingredients'),
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients_de',
            field=models.TextField(blank=True, null=True, verbose_name='Food ingredients'),
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients_en',
            field=models.TextField(blank=True, null=True, verbose_name='Food ingredients'),
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Food ingredients'),
        ),
        migrations.AddField(
            model_name='food',
            name='name_cs',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Food name'),
        ),
        migrations.AddField(
            model_name='food',
            name='name_de',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Food name'),
        ),
        migrations.AddField(
            model_name='food',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Food name'),
        ),
        migrations.AddField(
            model_name='food',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Food name'),
        ),
        migrations.AddField(
            model_name='food',
            name='notes_cs',
            field=models.TextField(blank=True, null=True, verbose_name='Food notes'),
        ),
        migrations.AddField(
            model_name='food',
            name='notes_de',
            field=models.TextField(blank=True, null=True, verbose_name='Food notes'),
        ),
        migrations.AddField(
            model_name='food',
            name='notes_en',
            field=models.TextField(blank=True, null=True, verbose_name='Food notes'),
        ),
        migrations.AddField(
            model_name='food',
            name='notes_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Food notes'),
        ),
    ]
