# Generated by Django 4.1.3 on 2022-11-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzlatekachny', '0003_food_order_alter_food_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='ingredients',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Food ingredients'),
        ),
        migrations.AlterField(
            model_name='food',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Food notes'),
        ),
    ]
