# Generated by Django 4.1.3 on 2022-11-18 07:39

import django.core.validators
from django.db import migrations, models
import uzlatekachny.models


class Migration(migrations.Migration):

    dependencies = [
        ('uzlatekachny', '0001_squashed_0004_alter_food_ingredients_alter_food_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='order',
            field=models.CharField(default=uzlatekachny.models.Food.next_order_nr, max_length=4, unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
