# Generated by Django 4.1.3 on 2022-11-18 07:41

from django.db import migrations, models
import uzlatekachny.models


class Migration(migrations.Migration):

    dependencies = [
        ('uzlatekachny', '0005_alter_food_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='order',
            field=models.CharField(default=uzlatekachny.models.Food.next_order_nr, max_length=4, unique=True),
        ),
    ]
