# Generated by Django 4.1.3 on 2022-11-19 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzlatekachny', '0007_alter_food_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['order']},
        ),
    ]
