# Generated by Django 4.1.3 on 2022-11-19 09:23

from django.db import migrations, models
import uzlatekachny.models


class Migration(migrations.Migration):

    dependencies = [
        ('uzlatekachny', '0008_alter_food_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='order',
            field=models.IntegerField(default=uzlatekachny.models.Food.next_order_nr),
        ),
    ]
