# Generated by Django 4.1.3 on 2022-11-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzlatekachny', '0009_alter_food_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['order', 'add_time']},
        ),
        migrations.AddField(
            model_name='food',
            name='add_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
