# Generated by Django 4.1.3 on 2022-11-20 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzlatekachny', '0010_alter_food_options_food_add_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['order', '-add_time']},
        ),
    ]
